# Generated by Django 4.2.7 on 2023-11-05 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 10, 10, 47, 204111)),
        ),
    ]
